[settings]
laddress = "192.168.1.2"
uaddress = "8.8.8.8"

[vars]
ip = "192.168.1.10"

[map]
personal.domain1 = "${ip}"
personal.domain2 = "192.168.42.86"
www.personal.domain3 = "192.168.1.1"

[exceptions]
www.personal.domain3 = "192.168.42.86"
